config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :show
  resources :projects, except: :show
  namespace :api do
    resources :tasks, only: %i[index show create update destroy] do
      member do
        patch :mark_as_completed, :mark_as_incompleted
      end
    end
    resources :projects, only: %i[index show create update destroy] do
      member do
        patch :mark_as_completed, :mark_as_incompleted
      end
    end
  end
  root 'tasks#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Project < ApplicationRecord
  include Completable
  validates :title, presence: true

  after_create_commit { broadcast_prepend_to 'projects', target: 'results', partial: 'projects/project', locals: { project: self }}

  after_update_commit { broadcast_update_to "projects", target: "project_#{self.id}", partial: "projects/project", locals: { project: self } }

  after_destroy_commit { broadcast_remove_to "projects", target: "project_#{self.id}" }

  after_save { broadcast_update_to "update_counts", target: "projects_frame", partial: "shared/projects_count" }
  after_destroy { broadcast_update_to "update_counts", target: "projects_frame", partial: "shared/projects_count" }


  has_one_attached :feature_image
end

app/controllers/api/projects_controller.rb
# frozen_string_literal: true

module Api
  class ProjectsController < ActionController::API
    before_action :set_project, only: %i[show update destroy mark_as_completed mark_as_incompleted]
    include HasImageUrl
    def index
      projects = Project.includes(:feature_image_attachment).order(created_at: :desc)
      projects = projects.where('title ILIKE ?', "%#{params[:query]}%") if params[:query].present?
      projects = projects.map do |project|
        with_image_url(project, :feature_image)
      end
      render json: projects
    end

    def create
      project = Project.new(project_params)

      if project.save
        render json: project, status: :created
      else
        render json: project.errors.to_json, status: :unprocessable_entity
      end
    end

    def update
      if @project.update(project_params)
        render json: @project, status: :ok
      else
        render json: @project.errors.to_json, status: :unprocessable_entity
      end
    end

    def show
      @project = with_image_url(@project, :feature_image)
      render json: @project, status: :ok
    end

    def destroy
      @project.destroy
      head :ok
    end

    def mark_as_completed
      @project.completed_at = Time.zone.now
      @project.save
      head :ok
    end

    def mark_as_incompleted
      @project.completed_at = nil
      @project.save
      head :ok
    end

    private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.except(:id).permit(:title, :completed_at, :feature_image)
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update destroy]

  # GET /projects
  def index
    @projects = Project.includes(:feature_image_attachment).order(created_at: :desc)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy!
    redirect_to projects_path, alert: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  rescue StandardError
    redirect_to projects_path
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :completed_at, :feature_image)
  end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/projects_helper.rb
# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents", target: "_top") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :feature_image %>
    <%= form.file_field :feature_image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if project.feature_image.attached? %>
      <%= image_tag project.feature_image.variant(resize_to_limit: [100, 100]) %>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :completed_at %>
    <%= form.datetime_field :completed_at, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_stream_from project %>
<div id="<%= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= project.title %>
  </p>

  <p class="my-5">
    <% if project.feature_image.attached? %>
      <%= image_tag project.feature_image.variant(resize_to_limit: [100, 100]) %>
    <% else %>
      <p>No image available</p>
    <% end %>
  </p>


  <p class="my-5">
    <strong class="block font-medium mb-1">Completed at:</strong>
    <%= l(project.completed_at, format: :long) unless project.completed_at.blank? %>
  </p>

  <div class="flex space-x-2">
    <%= link_to "Edit this project", edit_project_path(project), class: "rounded-lg py-3 px-5 bg-blue-400 inline-block font-medium text-white" %>
    <%= button_to "Destroy this project", project_path(project), method: :delete, class: "rounded-lg py-3 px-5 bg-red-800 text-white font-medium", form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>
  <hr class="mt-6">
</div>

app/views/projects/edit.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "rounded-lg py-3 ml-2 px-5 bg-blue-400 inline-block font-medium text-white" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this project", project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-800 text-white font-medium", form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="mx-auto w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to "New project", new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= turbo_stream_from :projects %>
  <div id="results" class="min-w-full">
    <%=render @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "rounded-lg py-3 ml-2 px-5 bg-blue-400 inline-block font-medium text-white" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto w-full">
  <%= turbo_stream_from dom_id(@project) %>
  <%= render @project %>

  <%= link_to "Edit this project", edit_project_path(@project), class: "mt-2 rrounded-lg py-3 px-5 bg-blue-400 inline-block font-medium text-white" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-400 inline-block font-medium text-white" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this project", project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium", form: { data: { turbo_confirm: 'Are you sure?' } } %>
  </div>
</div>