config/routes.rb
Rails.application.routes.draw do
  resources :tasks, except: :show
  resources :projects, except: :show
  namespace :api do
    resources :tasks, only: %i[index show create update destroy] do
      member do
        patch :mark_as_completed, :mark_as_incompleted
      end
    end
    resources :projects, only: %i[index show create update destroy] do
      member do
        patch :mark_as_completed, :mark_as_incompleted
      end
    end
  end
  root 'tasks#index'
end

app/views/layouts/_results_in_header.html.erb
<div class="flex space-x-4">
<%= link_to tasks_path, class: "flex items-center space-x-2" do %>
  <i class="fas fa-tasks mr-2"></i>
  Tasks
  <%= completed_count(Task) %>
<% end %>
<%= link_to projects_path, class: "flex items-center space-x-2" do %>
  <i class="fas fa-briefcase mr-2"></i>
  Projects
  <%= completed_count(Project) %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksControl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>
    <%= javascript_importmap_tags %>
    <%= action_cable_meta_tag  %>
  </head>

  <body>
    <nav class="bg-gray-800 p-4 text-white fixed w-full top-0">
      <div class="container mx-auto flex justify-between items-center">
        <%= link_to root_path, class: "text-lg font-bold" do %>
          <i class="fas fa-check-double m-2"></i>
        <% end %>
        <%= form_for :general_search, url: nil, data: { reflex: "submit->GeneralSearchReflex#search" }, html: { class: "flex items-center space-x-2" } do |f| %>
          <%= f.text_field :query, data: { reflex: "keyup->GeneralSearchReflex#search", reflex_dataset: "combined" }, class: "form-input bg-gray-700 text-white rounded px-2 py-1", placeholder: "Search..." %>
          <%= hidden_field_tag :current_controller, controller_name %>
          <%= f.submit "Search", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-4 rounded" %>
        <% end %>
        <div class="flex space-x-4">
          <%=turbo_stream_from "update_counts" %>
          <%= turbo_frame_tag 'tasks_frame' do %>
            <%= render partial: 'shared/tasks_count' %>
          <% end %>

          <%= turbo_frame_tag 'projects_frame' do %>
            <%= render partial: 'shared/projects_count' %>
          <% end %>
        </div>
      </div>
    </nav>
    <main class="container mx-auto mt-28 px-5">
      <%= flash_messages %>
      <%= yield %>
    </main>
  </body>
</html>